# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1xZDyewMFSuqqQlbyFm7jDC40F_ifUVrk
"""

def add(x, y):
    print("Answer =", x + y)

def subtract(x, y):
    print("Answer =", x - y)

def multiply(x, y):
    print("Answer =", x * y)

def divide(x, y):
    if y == 0:
        print("Division is not possible")
    else:
        print("Answer =", x / y)

num1 = int(input("Enter first number: "))
num2 = int(input("Enter second number: "))

print("1. Addition")
print("2. Subtraction")
print("3. Multiplication")
print("4. Division")

option = int(input("Choose an option: "))

if option == 1:
    add(num1, num2)
elif option == 2:
    subtract(num1, num2)
elif option == 3:
    multiply(num1, num2)
elif option == 4:
    divide(num1, num2)
else:
    print("Wrong choice")